### ISSUE TITLE
GitHub Pages build not triggered with GITHUB_TOKEN

### ISSUE THREAD

**Issue by maxmouchet** [JuliaDocs/Documenter.jl#1177]
According to https://github.com/JuliaDocs/Documenter.jl/pull/1165 `GITHUB_TOKEN`is sufficient for Documenter to push to `gh-pages`.

However it seems that this token is not allowed to trigger pages builds [1]:
> The `GITHUB_TOKEN` that is provided as a part of GitHub Actions doesn't have authorization to create any successive events, such as GitHub Pages builds. So while you can push to the `gh-pages` branch using the `GITHUB_TOKEN`, it won't spawn a GitHub Pages build. You'll need to create a personal access token and supply it to your GitHub Action as a secret. 

Hence, docs. are correctly pushed, but GitHub Pages are never updated.  
Is there any workaround ?

I tried to add a manual build trigger [2] in my [workflow](https://github.com/maxmouchet/HMMBase.jl/blob/dbeb087f4632a9a8013e5778ab37fa8b141368d2/.github/workflows/documentation.yml):
```yaml
- name: Build and deploy
  env:
    DOCUMENTER_DEBUG: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        julia --project=docs/ docs/make.jl
        curl -u maxmouchet:${GITHUB_TOKEN} -X POST https://api.github.com/repositories/164427411/pages/builds -H "Accept: application/vnd.github.mister-fantastic-preview+json"
```
but the GitHub API [returns](https://github.com/maxmouchet/HMMBase.jl/commit/dbeb087f4632a9a8013e5778ab37fa8b141368d2/checks?check_suite_id=307586853#step:5:149) the following error:
```json
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/repos/pages/#request-a-page-build"
}
```

[1] https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869
[2] https://stackoverflow.com/a/54088985
