### ISSUE TITLE
Load key: invalid format

### ISSUE THREAD

**Issue by wangjie212** [JuliaDocs/Documenter.jl#1515]
I followed the hosting documentation to deploy the documentation for the TSSOS package. But I got the following error in the workflow (GitHub Actions):

> Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/home/runner/.ssh/known_hosts).
Load key "/home/runner/work/TSSOS/TSSOS/docs/.documenter": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:wangjie212/TSSOS.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/FuXcO/src/Documenter.jl:554

Any idea to fix this issue? I use the Windows 10 system and the key pair was generated by DocumenterTools.genkeys.

**Comment by mortenpi** [comment]
It looks like something went wrong when adding `DOCUMENTER_KEY` to the repo. I would suggest just trying to regenerate the keys

**Comment by michakraus** [comment]
I see a similar issue when generating docs for a pull request using GitHub actions. If I deploy docs for master or releases, everything works fine. I regenerated the keys, but that didn't help.

In the output (please see below) there is a hint `Using 'master' as the name for the initial branch [...]`, which looks somewhat fishy, but it's not really clear to me, what's going on there.

My `Documenter.yml` looks like this:
```
name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build(); Pkg.precompile();'
      - name: Build Tutorial
        run: julia --project tutorial.jl
        working-directory: docs
      - name: Build and deploy Documentation
        run: julia --project make.jl
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```

and this is the output I get:
```
...
┌ Info: Deployment criteria for deploying preview build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaGNI/GeometricIntegrators.jl" occurs in repo="github.com/JuliaGNI/GeometricIntegrators.jl"
│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number
│ - ✔ `push_preview` keyword argument to deploydocs is `true`
│ - ✔ ENV["GITHUB_ACTOR"] exists
│ - ✔ ENV["DOCUMENTER_KEY"] exists
└ Deploying: ✔
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /tmp/jl_ICG8Xb/.git/
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/home/runner/.ssh/known_hosts).
Load key "/home/runner/work/GeometricIntegrators.jl/GeometricIntegrators.jl/docs/.documenter": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:JuliaGNI/GeometricIntegrators.jl
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/6vUwN/src/Documenter.jl:552
┌ Error: Failed to push:
│   exception =
│    failed process: Process(`git fetch upstream`, ProcessExited(128)) [128]
│    
│    Stacktrace:
│     [1] pipeline_error at ./process.jl:525 [inlined]
│     [2] run(::Cmd; wait::Bool) at ./process.jl:440
│     [3] run at ./process.jl:438 [inlined]
│     [4] (::Documenter.var"#git_commands#27"{String,SubString{String},String,Array{Any,1},Bool,String,String})(::String) at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:550
│     [5] (::Documenter.var"#26#32"{String})() at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:655
│     [6] cd(::Documenter.var"#26#32"{String}, ::String) at ./file.jl:104
│     [7] #25 at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:655 [inlined]
│     [8] withenv(::Documenter.var"#25#31"{String,String}, ::Pair{String,String}) at ./env.jl:161
│     [9] (::Documenter.var"#24#30"{String,String,SubString{String},String})(::String, ::IOStream) at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:654
│     [10] mktemp(::Documenter.var"#24#30"{String,String,SubString{String},String}, ::String) at ./file.jl:686
│     [11] mktemp(::Function) at ./file.jl:684
│     [12] git_push(::String, ::String, ::String; branch::String, dirname::String, target::String, sha::SubString{String}, devurl::String, versions::Array{Any,1}, forcepush::Bool, deploy_config::Documenter.GitHubActions, subfolder::String, is_preview::Bool) at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:639
│     [13] #18 at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:504 [inlined]
│     [14] mktempdir(::Documenter.var"#18#20"{SubString{String},String,String,String,String,Array{Any,1},Bool,Documenter.GitHubActions,String,String,String,Bool}, ::String; prefix::String) at ./file.jl:709
│     [15] mktempdir(::Function, ::String) at ./file.jl:707 (repeats 2 times)
│     [16] (::Documenter.var"#17#19"{String,String,String,Nothing,String,Array{Any,1},Bool,Documenter.GitHubActions,String,String,String,Bool})() at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:503
│     [17] cd(::Documenter.var"#17#19"{String,String,String,Nothing,String,Array{Any,1},Bool,Documenter.GitHubActions,String,String,String,Bool}, ::String) at ./file.jl:104
│     [18] deploydocs(; root::String, target::String, dirname::String, repo::String, branch::String, repo_previews::String, branch_previews::String, deps::Nothing, make::Nothing, devbranch::String, devurl::String, versions::Array{Any,1}, forcepush::Bool, deploy_config::Documenter.GitHubActions, push_preview::Bool) at /home/runner/.julia/packages/Documenter/6vUwN/src/Documenter.jl:480
│     [19] top-level scope at /home/runner/work/GeometricIntegrators.jl/GeometricIntegrators.jl/docs/make.jl:73
│     [20] include(::Function, ::Module, ::String) at ./Base.jl:380
│     [21] include(::Module, ::String) at ./Base.jl:368
│     [22] exec_options(::Base.JLOptions) at ./client.jl:296
│     [23] _start() at ./client.jl:506
└ @ Documenter ~/.julia/packages/Documenter/6vUwN/src/Documenter.jl:660
```
