### ISSUE TITLE
Building document for a tag on Github

### ISSUE THREAD

**Issue by ericqu** [JuliaDocs/Documenter.jl#1729]
My documentation works fine when I run it on the "dev".
However, I now would like to add documentation for each future new tagged version.
My package is not registered, as I don't think there is yet enough interest.

The documentation indicates how to work with "Tagbot"; however, I suppose this won't be relevant since the package is not registered. 

Is there a way to generate the documentation using only the tags from Github?

for reference, here is the setup for `Documenter`
```
name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
```
and the `make.jl`
```julia
push!(LOAD_PATH,"../src/")
using Documenter
using StatsModels, DataFrames, VegaLite
using LinearRegression

makedocs(sitename="LinearRegression.jl", modules = [LinearRegression] ,
    pages = Any[
        "Home" => "index.md",
        "Tutorials" => Any[
            "Basic" => "basic_tutorial.md",
            "Multiple regression" => "multi_tutorial.md" ]
    ])

deploydocs(
    repo = "github.com/ericqu/LinearRegression.jl.git",
    push_preview = false,
    devbranch = "main",
    devurl = "dev",
)
```
