### ISSUE TITLE
Build not triggered by TagBot

### ISSUE THREAD

**Issue by yufongpeng** [JuliaDocs/Documenter.jl#1815]
I followed the documentation, but only `dev` and preview were successfully built when pushing to master. After new version was tagged, no workflow was initiated.
Here's my `deploydoc`:
```julia
deploydocs(
    repo = "github.com/yufongpeng/MixedAnova.jl.git",
    push_preview = true, 
    devbranch = "master"
)
```
and this is my workflow for documenter:
```
name: Documentation

on:
  push:
    branches: 
      - 'master'
      - 'release-*'
    tags: 
      - 'v*'
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```
Is there something wrong with my settings?
