### ISSUE TITLE
Python SymPy dependency of custom package not loading when building documentation

### ISSUE THREAD

**Issue by arthur-fyon** [JuliaDocs/Documenter.jl#2270]
Hi,

I am building a custom package whose only dependency are SymPy and Conda. Everything worked well on AppVeyor and Travis but when it comes to the Documenter job on github actions, I get this error:

```
ERROR: LoadError: InitError: PyError (PyImport_ImportModule

The Python package sympy could not be imported by pyimport. Usually this means
that you did not install sympy in the Python version being used by PyCall.

PyCall is currently configured to use the Python version at:

/usr/bin/python3

and you should use whatever mechanism you usually use (apt-get, pip, conda,
etcetera) to install the Python package containing the sympy module.
```

Here is my *documenter.yml* file
```
name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.add("Conda"); Pkg.add("SymPy"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
```

and my *make.jl* file

```
using Documenter
using NmodController

makedocs(
    sitename = "NmodController",
    format = Documenter.HTML(),
    pages=[
        "Home" => "index.md",
        "Initializing a conductance based model" =>
                    ["How to initialize an ionic current?"          => "initializing/current.md",
                     "How to initialize a conductance based model?" => "initializing/neuron.md",
                     "Examples of existing models"                  => "initializing/examples.md",],
        "Computing dynamical input conductances (DICs)" =>
                    ["How to compute DICs and sensitivity matrix?" => "computing/DICs.md",
                     "Examples of existing models"                 => "computing/examples.md",],
        "Simulating with DifferentialEquations.jl" =>
                    ["How to write ODE functions file?" => "simulating/files.md",
                     "Examples of existing models"      => "simulating/examples.md",],
        "Types/Methods/Functions" => "typesMethodsFunctions.md",
    ],
    modules = Module[NmodController]
)

# Documenter can also automatically deploy documentation to gh-pages.
# See "Hosting Documentation" and deploydocs() in the Documenter manual
# for more information.
deploydocs(
    repo = "github.com/arthur-fyon/NmodController.jl"
)
```

The error occurs at `using NmodController` (my custom package) in the *make.jl* file.¨

However, if I do not include NmodController (and so modules is empty), everything works fine but I cannot use the autodoc block and so on.

If anybody could help me.

Thanks a lot in advance.

Have a nice day,
Arthur
