### ISSUE TITLE
Travis CI hangs forever after deploying docs.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaDocs/Documenter.jl#351]
Hi,

I encountered a problem that Travis CI hangs forever after deploying docs. Here is the log of a build:
https://travis-ci.org/bicycle1885/EzXML.jl/jobs/175317593.

I'm not sure whether this is due to this package, but this started to happen just after started to use `deploydocs` to deploy docs to GitHub pages. Also, this does not happen on other platforms that does not deploy docs (I'm using Julia 0.5 on Linux in deployment). So, I thought this may be related to its process.

[.travis.yml](https://github.com/bicycle1885/EzXML.jl/blob/master/.travis.yml):
```yml
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("EzXML"); Pkg.test("EzXML"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  # - julia -e 'cd(Pkg.dir("EzXML")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("EzXML")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("EzXML")); include(joinpath("docs", "make.jl"))'
```

[make.jl](https://github.com/bicycle1885/EzXML.jl/blob/master/docs/make.jl):
```julia
using Documenter
using EzXML

makedocs(
    format=:html,
    sitename="EzXML.jl",
    pages=["index.md", "manual.md", "references.md", "devnotes.md"])

deploydocs(
    repo="github.com/bicycle1885/EzXML.jl.git",
    julia="0.5",
    target="build",
    deps=nothing,
    make=nothing)
```
