### ISSUE TITLE
Specify fonts on a per-project basis

### ISSUE THREAD

**Issue by ararslan** [JuliaDocs/Documenter.jl#461]
Personally I quite dislike the default monospace font, Ubuntu Mono. I have no issues with the rest of the Documenter style, so what I'd like to be able to do is override a particular default, in this case just the font. (Unless of course you're open to a different default. 😉) Is this currently possible? Is there a way to e.g. inject
```css
pre, code {
  font-family: 'Source Code Pro', 'Andale Mono WT', courier, monospace !important;
}
```
?
