### ISSUE TITLE
Unable to generate docs in Travis

### ISSUE THREAD

**Issue by danmrc** [JuliaDocs/Documenter.jl#897]
Hi,

I was following the documentation and trying to create my documentation in travis. I used this piece of code, that is available [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) 

```
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
```
Which generates this error: 

```
The program 'julia' is currently not installed. To run 'julia' please ask your administrator to install the package 'julia'
The command "julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'" exited with 127.
```
After some attempts, I changed the code to this:

```
language: julia
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
```
Which generates another error:

```
ERROR: LoadError: ArgumentError: Package Documenter not found in current path:
- Run `import Pkg; Pkg.add("Documenter")` to install the Documenter package.
```

This is my first time using both this package and Travis, so it must be some silly mistake. But I was not able to find any answer. 

Btw, I include Documenter as a dependence of my package using `] add Documenter`

Thanks
