### ISSUE TITLE
Using a different font

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#973]
How can I use a different font, for either the core font or the code font when using `Documenter` and its default HTML output?

Material+MkDocs seems to offer a quite convenient feature where you can use any font offered by Google Fonts. For example, in some other documentations I've built using the Markdown output, I can put in my `mkdocs.yml`:
```
theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'teal'
  font:
    text: 'Montserrat'
    code: 'Source Code Pro'
```
and it will use different fonts.

Is it at all possible to change the default font? The current documentation seems to say no: https://juliadocs.github.io/Documenter.jl/stable/search/?q=font

Would be cool if you allowed a keyword font to `makedocs`.
